version: '3.7'

services:
  web:
    build: ./webserver
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./webserver/:/usr/src/webserver/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgis/postgis:12-master
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

      

volumes:
  postgres_data:
