# Generated by Django 3.0.7 on 2020-06-22 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('want_to_be_matched', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=200)),
                ('group', models.CharField(default='None', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=700)),
                ('last_name', models.CharField(max_length=700)),
                ('phone_number', models.IntegerField(default=0, null=True)),
                ('collaborator', models.BooleanField(default=False)),
                ('ideamaker', models.BooleanField(default=False)),
                ('want_to_be_matched', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User_Language',
            fields=[
                ('user_language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='Landing_page.Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Up_For_Matched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=100)),
                ('colab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Landing_page.Collaboration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Up_For',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_free_text', models.CharField(default='None', max_length=200)),
                ('interest', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='Landing_page.Skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passion_Matched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=100)),
                ('colab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Landing_page.Collaboration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passion_free_text', models.CharField(default='None', max_length=200)),
                ('passion', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='Landing_page.Skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('colab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Landing_page.Collaboration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='collaboration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Colab_Up_For',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_free_text', models.CharField(default='None', max_length=200)),
                ('colab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Landing_page.Collaboration')),
                ('interest', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='Landing_page.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Colab_Passion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passion_free_text', models.CharField(default='None', max_length=200)),
                ('colab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Landing_page.Collaboration')),
                ('passion', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='Landing_page.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Colab_Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Landing_page.Collaboration')),
                ('language', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='Landing_page.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Colab_Business_Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_free_text', models.CharField(default='None', max_length=200)),
                ('colab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Landing_page.Collaboration')),
                ('experience', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='Landing_page.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Colab_Assigned_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_skill_free_text', models.CharField(default='None', max_length=200)),
                ('assigned_skill', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='Landing_page.Skill')),
                ('colab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Landing_page.Collaboration')),
            ],
        ),
        migrations.CreateModel(
            name='Business_Experience_Matched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=100)),
                ('colab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Landing_page.Collaboration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business_Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_free_text', models.CharField(default='None', max_length=200)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Landing_page.Skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assigned_Skill_Matched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=100)),
                ('colab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Landing_page.Collaboration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assigned_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_skill_free_text', models.CharField(default='None', max_length=200)),
                ('assigned_skill', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='Landing_page.Skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
